[build]
  base = "masuot-simulator"
  command = "npm run build -- --configuration production"
  publish = "dist/masuot-simulator/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200