[build]
  base = "masuot-simulator"
  command = "npm run build --configuration production"
  publish = "dist/frontend"

# 🔥 חשוב ל-Angular (routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200